import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { serializeProject } from './serializer.js';
import { encryptData } from './crypto.js';

/**
 * Builds the runtime bootstrap script for the standalone executable app.js
 * @param {object} container 
 * @returns {string} executable JS code
 */
export function buildBootstrapCode(container) {
  const containerJson = JSON.stringify(container, null, 2);

  return `#!/usr/bin/env node
/**
 * Protected Project Executable
 * Generated by Project Protector CLI (AES-256-GCM + scrypt)
 * 
 * WARNING: This file contains encrypted project bytecode.
 * Execution requires the decryption password.
 */

import crypto from 'crypto';
import zlib from 'zlib';
import path from 'path';
import vm from 'vm';
import { Module, createRequire } from 'module';
import { execSync } from 'child_process';
import readline from 'readline';
import { fileURLToPath } from 'url';

const require = createRequire(import.meta.url);
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CONTAINER = ${containerJson};

function isEsmCode(code) {
  if (!code) return false;
  return (
    /(?:^|\\n)\\s*import\\s+[\\s\\S]*?from\\s+['"]/.test(code) ||
    /(?:^|\\n)\\s*import\\s+['"][^'"]+['"]/.test(code) ||
    /(?:^|\\n)\\s*export\\s+(?:default|const|let|var|function|class|async|\\{)/.test(code) ||
    /import\\.meta/.test(code) ||
    /(?:const|let|var)\\s+__filename\\s*=/.test(code) ||
    /(?:const|let|var)\\s+__dirname\\s*=/.test(code)
  );
}

function transformEsmToCjs(code) {
  if (!code || !isEsmCode(code)) return code;
  let transformed = code;
  const exportedSymbols = new Set();

  transformed = transformed.replace(
    /(?:^|\\n)\\s*(?:const|let|var)\\s+__filename\\s*=\\s*[^;\\n]+;?/g,
    '\\n/* __filename injected by loader */'
  );
  transformed = transformed.replace(
    /(?:^|\\n)\\s*(?:const|let|var)\\s+__dirname\\s*=\\s*[^;\\n]+;?/g,
    '\\n/* __dirname injected by loader */'
  );

  transformed = transformed
    .replace(/import\\.meta\\.url/g, "require('url').pathToFileURL(__filename).href")
    .replace(/import\\.meta\\.dirname/g, '__dirname')
    .replace(/import\\.meta\\.filename/g, '__filename');

  transformed = transformed.replace(
    /(?:^|\\n)\\s*import\\s+['"]([^'"]+)['"];?/g,
    (m, p1) => '\\nrequire(\\'' + p1 + '\\');'
  );

  transformed = transformed.replace(
    /(?:^|\\n)\\s*import\\s+\\*\\s+as\\s+([a-zA-Z0-9_$]+)\\s+from\\s+['"]([^'"]+)['"];?/g,
    (m, name, modPath) => '\\nconst ' + name + ' = require(\\'' + modPath + '\\');'
  );

  transformed = transformed.replace(
    /(?:^|\\n)\\s*import\\s+([a-zA-Z0-9_$]+)\\s*,\\s*\\{([\\s\\S]*?)\\}\\s+from\\s+['"]([^'"]+)['"];?/g,
    (m, defName, namedGroup, modPath) => {
      const tempVar = '_m_' + Math.random().toString(36).slice(2, 8);
      const namedBindings = namedGroup
        .split(',')
        .map((p) => p.trim())
        .filter(Boolean)
        .map((p) => {
          if (/\\s+as\\s+/.test(p)) {
            const [orig, alias] = p.split(/\\s+as\\s+/);
            return orig.trim() + ': ' + alias.trim();
          }
          return p;
        })
        .join(', ');
      return '\\nconst ' + tempVar + ' = require(\\'' + modPath + '\\'); const ' + defName + ' = ' + tempVar + ' && ' + tempVar + '.default !== undefined ? ' + tempVar + '.default : ' + tempVar + '; const { ' + namedBindings + ' } = ' + tempVar + ';';
    }
  );

  transformed = transformed.replace(
    /(?:^|\\n)\\s*import\\s*\\{([\\s\\S]*?)\\}\\s*from\\s*['"]([^'"]+)['"];?/g,
    (m, namedGroup, modPath) => {
      const namedBindings = namedGroup
        .split(',')
        .map((p) => p.trim())
        .filter(Boolean)
        .map((p) => {
          if (/\\s+as\\s+/.test(p)) {
            const [orig, alias] = p.split(/\\s+as\\s+/);
            return orig.trim() + ': ' + alias.trim();
          }
          return p;
        })
        .join(', ');
      return '\\nconst { ' + namedBindings + ' } = require(\\'' + modPath + '\\');';
    }
  );

  transformed = transformed.replace(
    /(?:^|\\n)\\s*import\\s+([a-zA-Z0-9_$]+)\\s+from\\s+['"]([^'"]+)['"];?/g,
    (m, defName, modPath) => {
      const tempVar = '_def_' + Math.random().toString(36).slice(2, 8);
      return '\\nconst ' + tempVar + ' = require(\\'' + modPath + '\\'); const ' + defName + ' = ' + tempVar + ' && ' + tempVar + '.default !== undefined ? ' + tempVar + '.default : ' + tempVar + ';';
    }
  );

  transformed = transformed.replace(
    /(?:^|\\n)\\s*export\\s+default\\s+([\\s\\S]*?);?(?=\\n|$)/g,
    (m, expr) => '\\nmodule.exports = ' + expr.trim() + '; module.exports.default = ' + expr.trim() + ';'
  );

  transformed = transformed.replace(
    /(?:^|\\n)\\s*export\\s+(async\\s+function\\*?|function\\*?|class)\\s+([a-zA-Z0-9_$]+)\\b/g,
    (m, kind, name) => {
      exportedSymbols.add(name);
      return '\\n' + kind + ' ' + name;
    }
  );

  transformed = transformed.replace(
    /(?:^|\\n)\\s*export\\s+(const|let|var)\\s+([a-zA-Z0-9_$]+)\\s*=/g,
    (m, kw, name) => {
      exportedSymbols.add(name);
      return '\\n' + kw + ' ' + name + ' = exports.' + name + ' =';
    }
  );

  transformed = transformed.replace(
    /(?:^|\\n)\\s*export\\s*\\{([\\s\\S]*?)\\};?/g,
    (m, group) => {
      const lines = group
        .split(',')
        .map((p) => p.trim())
        .filter(Boolean)
        .map((p) => {
          if (/\\s+as\\s+/.test(p)) {
            const [orig, alias] = p.split(/\\s+as\\s+/);
            return 'exports.' + alias.trim() + ' = ' + orig.trim() + ';';
          }
          return 'exports.' + p + ' = ' + p + ';';
        });
      return '\\n' + lines.join('\\n');
    }
  );

  transformed = transformed.replace(
    /(?:^|\\n)\\s*export\\s*\\*\\s*from\\s*['"]([^'"]+)['"];?/g,
    (m, modPath) => '\\nObject.assign(exports, require(\\'' + modPath + '\\'));'
  );

  for (const name of exportedSymbols) {
    transformed += '\\nif (typeof ' + name + ' !== \\'undefined\\') exports.' + name + ' = ' + name + ';';
  }

  return transformed;
}

function promptPassword(query = '🔑 Enter decryption password: ') {
  return new Promise((resolve) => {
    if (!process.stdin.isTTY) {
      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
        terminal: false,
      });
      rl.question(query, (answer) => {
        rl.close();
        resolve(answer.trim());
      });
      return;
    }

    process.stdout.write(query);
    let password = '';
    const wasRaw = process.stdin.isRaw;
    process.stdin.setRawMode(true);
    process.stdin.resume();
    process.stdin.setEncoding('utf8');

    const onData = (chunk) => {
      for (const char of chunk) {
        if (char === '\\r' || char === '\\n' || char === '\\u0004') {
          process.stdin.setRawMode(wasRaw);
          process.stdin.pause();
          process.stdin.removeListener('data', onData);
          process.stdout.write('\\n');
          resolve(password);
          return;
        }
        if (char === '\\u0003') {
          process.stdin.setRawMode(wasRaw);
          process.stdout.write('\\n');
          process.exit(130);
        }
        if (char === '\\u0008' || char === '\\u007f') {
          if (password.length > 0) {
            password = password.slice(0, -1);
            process.stdout.write('\\b \\b');
          }
        } else if (char.charCodeAt(0) >= 32) {
          password += char;
          process.stdout.write('*');
        }
      }
    };

    process.stdin.on('data', onData);
  });
}

function decryptPayload(container, password) {
  if (container.runtime) {
    const k1 = Buffer.from(container.runtime.k1, 'base64');
    const k2 = Buffer.from(container.runtime.k2, 'base64');
    const key = Buffer.alloc(32);
    for (let i = 0; i < 32; i++) {
      key[i] = k1[i] ^ k2[i];
    }
    const iv = Buffer.from(container.runtime.iv, 'base64');
    const tag = Buffer.from(container.runtime.tag, 'base64');
    const payload = Buffer.from(container.runtime.payload, 'base64');

    try {
      const decipher = crypto.createDecipheriv('aes-256-gcm', key, iv, {
        authTagLength: 16,
      });
      decipher.setAuthTag(tag);
      const decrypted = Buffer.concat([decipher.update(payload), decipher.final()]);
      return decrypted;
    } finally {
      key.fill(0);
    }
  }

  const target = container.restore || container;
  const salt = Buffer.from(target.salt, 'base64');
  const iv = Buffer.from(target.iv, 'base64');
  const tag = Buffer.from(target.tag, 'base64');
  const payload = Buffer.from(target.payload, 'base64');

  const key = crypto.scryptSync(password || '', salt, 32, {
    N: 16384,
    r: 8,
    p: 1,
    maxmem: 32 * 1024 * 1024,
  });

  try {
    const decipher = crypto.createDecipheriv('aes-256-gcm', key, iv, {
      authTagLength: 16,
    });
    decipher.setAuthTag(tag);

    const decrypted = Buffer.concat([decipher.update(payload), decipher.final()]);
    return decrypted;
  } catch (err) {
    throw new Error('Authentication failed: Incorrect password or corrupted container');
  } finally {
    key.fill(0);
  }
}

function decompressProject(buffer) {
  let decompressed;
  try {
    decompressed = zlib.brotliDecompressSync(buffer);
  } catch {
    try {
      decompressed = zlib.gunzipSync(buffer);
    } catch {
      throw new Error('Decompression failed');
    }
  }
  return JSON.parse(decompressed.toString('utf8'));
}

function loadVirtualEnv(project) {
  if (!project.files) return;
  const envKey = project.files['.env'] ? '.env' : project.files['.env.local'] ? '.env.local' : null;
  if (!envKey) return;

  try {
    const raw = Buffer.from(project.files[envKey], 'base64').toString('utf8');
    const lines = raw.split(/\\r?\\n/);
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIndex = trimmed.indexOf('=');
      if (eqIndex > 0) {
        const key = trimmed.slice(0, eqIndex).trim();
        let val = trimmed.slice(eqIndex + 1).trim();
        if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
          val = val.slice(1, -1);
        }
        if (process.env[key] === undefined) {
          process.env[key] = val;
        }
      }
    }
  } catch (err) {}
}

function ensureDependenciesInstalled(project) {
  if (!project.files || !project.files['package.json']) return;

  try {
    const pkgContent = Buffer.from(project.files['package.json'], 'base64').toString('utf8');
    const pkg = JSON.parse(pkgContent);
    const deps = Object.keys(pkg.dependencies || {});

    if (deps.length > 0) {
      const missing = deps.filter((dep) => {
        try {
          Module._resolveFilename(dep, { paths: Module._nodeModulePaths(process.cwd()) }, false);
          return false;
        } catch {
          return true;
        }
      });

      if (missing.length > 0) {
        console.log('\\n\\x1b[36m📦 First run detected on this machine.\\x1b[0m');
        console.log('⚡ Automatically installing missing dependencies: \\x1b[33m' + missing.join(', ') + '\\x1b[0m...');
        execSync('npm install ' + missing.join(' ') + ' --no-audit --no-fund', {
          stdio: 'inherit',
          cwd: process.cwd(),
        });
        console.log('\\x1b[32m✅ Dependencies installed successfully! Launching in-memory execution...\\x1b[0m\\n');
      }
    }
  } catch (err) {
    console.warn('⚠️ Dependency auto-installer note:', err.message);
  }
}

class InMemoryLoader {
  constructor(project) {
    this.entry = project.entry.replace(/\\\\/g, '/');
    this.virtualFiles = new Map();
    this.moduleCache = new Map();

    for (const [relPath, base64Content] of Object.entries(project.files)) {
      const normalized = path.posix.normalize(relPath.replace(/\\\\/g, '/')).replace(/^\\.\\//, '');
      this.virtualFiles.set(normalized, Buffer.from(base64Content, 'base64'));
    }
  }

  resolvePath(request, parentVirtualDir = '.') {
    if (Module.isBuiltin(request)) {
      return { isVirtual: false, nativeModule: true };
    }

    if (request.startsWith('./') || request.startsWith('../') || request.startsWith('/')) {
      const combined = request.startsWith('/')
        ? path.posix.normalize(request.slice(1))
        : path.posix.normalize(path.posix.join(parentVirtualDir, request));

      const candidates = [
        combined,
        combined + '.js',
        combined + '.cjs',
        combined + '.mjs',
        combined + '.json',
        path.posix.join(combined, 'index.js'),
        path.posix.join(combined, 'index.json'),
      ];

      for (const candidate of candidates) {
        const clean = candidate.replace(/^\\.\\//, '');
        if (this.virtualFiles.has(clean)) {
          return { isVirtual: true, virtualPath: clean };
        }
      }

      const pkgPath = path.posix.join(combined, 'package.json').replace(/^\\.\\//, '');
      if (this.virtualFiles.has(pkgPath)) {
        try {
          const pkgData = JSON.parse(this.virtualFiles.get(pkgPath).toString('utf8'));
          if (pkgData.main) {
            const mainFile = path.posix.join(combined, pkgData.main).replace(/^\\.\\//, '');
            if (this.virtualFiles.has(mainFile)) {
              return { isVirtual: true, virtualPath: mainFile };
            }
            if (this.virtualFiles.has(mainFile + '.js')) {
              return { isVirtual: true, virtualPath: mainFile + '.js' };
            }
          }
        } catch {}
      }
    }

    return { isVirtual: false };
  }

  loadVirtualModule(virtualPath) {
    const cleanPath = path.posix.normalize(virtualPath).replace(/^\\.\\//, '');

    if (this.moduleCache.has(cleanPath)) {
      return this.moduleCache.get(cleanPath).exports;
    }

    if (!this.virtualFiles.has(cleanPath)) {
      throw new Error('Cannot find virtual module \\'' + virtualPath + '\\' in memory');
    }

    const fileBuffer = this.virtualFiles.get(cleanPath);
    const virtualDir = path.posix.dirname(cleanPath);
    const fakeFilename = path.resolve(process.cwd(), cleanPath);
    const fakeDirname = path.resolve(process.cwd(), virtualDir);

    const mod = new Module(fakeFilename, null);
    mod.filename = fakeFilename;
    mod.paths = Module._nodeModulePaths(process.cwd());
    this.moduleCache.set(cleanPath, mod);

    if (cleanPath.endsWith('.json')) {
      mod.exports = JSON.parse(fileBuffer.toString('utf8'));
      return mod.exports;
    }

    const customRequire = (specifier) => {
      const resolved = this.resolvePath(specifier, virtualDir);

      if (resolved.isVirtual) {
        return this.loadVirtualModule(resolved.virtualPath);
      }

      if (resolved.nativeModule) {
        return Module._load(specifier, null, false);
      }

      try {
        return Module._load(specifier, mod, false);
      } catch {
        return require(specifier);
      }
    };

    customRequire.resolve = (specifier) => {
      const resolved = this.resolvePath(specifier, virtualDir);
      if (resolved.isVirtual) {
        return path.resolve(process.cwd(), resolved.virtualPath);
      }
      return require.resolve(specifier, { paths: [fakeDirname, process.cwd()] });
    };

    customRequire.main = process.mainModule || mod;
    customRequire.cache = {};

    const rawCode = fileBuffer.toString('utf8');
    const code = transformEsmToCjs(rawCode);

    const wrapper = vm.compileFunction(
      code,
      ['exports', 'require', 'module', '__filename', '__dirname'],
      {
        filename: fakeFilename,
        lineOffset: 0,
        displayErrors: true,
      }
    );

    wrapper.call(mod.exports, mod.exports, customRequire, mod, fakeFilename, fakeDirname);
    mod.loaded = true;

    return mod.exports;
  }

  run() {
    return this.loadVirtualModule(this.entry);
  }
}

async function main() {
  let decryptedBuffer;
  try {
    decryptedBuffer = decryptPayload(CONTAINER, process.env.PROJECT_PASSWORD);
  } catch (err) {
    console.error('❌ ' + err.message);
    process.exit(1);
  }

  const project = decompressProject(decryptedBuffer);

  // 1. Automatically load in-memory .env variables into process.env
  loadVirtualEnv(project);

  // 2. Auto-install missing node_modules on first run
  ensureDependenciesInstalled(project);

  const loader = new InMemoryLoader(project);

  try {
    loader.run();
  } catch (err) {
    console.error('💥 Runtime Error in protected project:', err);
    process.exit(1);
  }
}

main().catch((err) => {
  console.error('Fatal execution error:', err);
  process.exit(1);
});

export {
  CONTAINER,
  decryptPayload,
  decompressProject,
  InMemoryLoader,
};
`;
}

/**
 * Protects a project directory into an encrypted executable file
 * @param {string} projectDir 
 * @param {string} outputPath 
 * @param {string} password 
 * @param {string|null} userEntry 
 * @returns {{ outputPath: string, fileCount: number, originalSize: number, compressedSize: number }}
 */
export function packProject(projectDir, outputPath, password, userEntry = null) {
  const { compressedBuffer, entry, fileCount, totalBytes } = serializeProject(projectDir, userEntry);

  // 1. Generate runtime key & IV for zero-password execution
  const runtimeKey = crypto.randomBytes(32);
  const runtimeIv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv('aes-256-gcm', runtimeKey, runtimeIv, { authTagLength: 16 });
  const runtimePayload = Buffer.concat([cipher.update(compressedBuffer), cipher.final()]);
  const runtimeTag = cipher.getAuthTag();

  // XOR mask for runtime key
  const mask = crypto.randomBytes(32);
  const maskedKey = Buffer.alloc(32);
  for (let i = 0; i < 32; i++) {
    maskedKey[i] = runtimeKey[i] ^ mask[i];
  }
  runtimeKey.fill(0);

  // 2. Encrypt with secret password for restore
  const restoreVault = encryptData(compressedBuffer, password);

  const container = {
    version: 2,
    entry,
    runtime: {
      iv: runtimeIv.toString('base64'),
      tag: runtimeTag.toString('base64'),
      payload: runtimePayload.toString('base64'),
      k1: maskedKey.toString('base64'),
      k2: mask.toString('base64'),
    },
    restore: {
      salt: restoreVault.salt,
      iv: restoreVault.iv,
      tag: restoreVault.tag,
      payload: restoreVault.payload,
    },
  };

  const outputCode = buildBootstrapCode(container);

  // Ensure output directory exists
  const resolvedOutput = path.resolve(outputPath);
  const outputDir = path.dirname(resolvedOutput);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(resolvedOutput, outputCode, { mode: 0o755 });

  return {
    outputPath: resolvedOutput,
    fileCount,
    originalSize: totalBytes,
    compressedSize: runtimePayload.length,
  };
}
